### ISSUE TITLE
coffeetags not found?

### ISSUE THREAD

**Issue by kaushalmodi** [fishman/ctags#131]
Hi,

I don't use coffeescript and so I don't have to have coffeetags installed.

I get this error when I run "ctags --help"

$MY_USR_LOCAL//libexec/ctags/drivers/coffeetags: line 31: coffeetags: command not found

How can I make ctags not look for coffeetags?

Thanks.

**Comment by masatake** [comment]
Try the code of HEAD; the warning message you reported will be suppressed with --quiet option.

**Comment by kaushalmodi** [comment]
Thanks it works!

This is probably not a big deal, but `ctags --help --quiet` does not work but `ctags --quiet --help` works as expected in quietening the warning.  I will anyways alias `ctags` to `ctags --quiet`. So it will not matter to me.
