### ISSUE TITLE
json parser goes mad with cities_light.json (un-prettified)

### ISSUE THREAD

**Issue by blueyed** [fishman/ctags#201]
TEST CASE:
1. wget https://gist.githubusercontent.com/blueyed/11b8995a5d42e755d636/raw/4afa26c200d4e39cba3c15f337e902e8d306953e/cities_light.json
2. ctags -f- cities_light.json

When run through `json_pp` to prettify it, it works:

1. https://gist.github.com/blueyed/11b8995a5d42e755d636/raw/01b5232d2e2a3de81175497781b1e3a05aae908a/cities_light_pp.json
2. ctags -f- cities_light_pp.json

This might indicate some problem where too long lines are not handled properly in the parser.

Apart from that I'm not sure if this parser should be enabled by default, given how much data it adds to tags files.

**Comment by b4n** [comment]
What is exactly the problem you have with the first run?  From what I can see it works just fine, but as CTags tries to put in the line that matched the tags it produces a *huge* output -- and I mean *very huge*.  See #163 that I reported for this very reason (I suffered from it with the JS parser, but the same applies to any one).

Try with `--excmd=number` and it should be all fine (I get the very same output with both of your files that way).

**Comment by b4n** [comment]
Out of curiosity I'm trying to generate the tag file with a default (pattern) excmd to see how huge it'd be, and so far the output file is more than 18G and running.  I'll keep you posted :)

**Comment by blueyed** [comment]
While using `--excmd=number` fixes it, the problem with the first command is that it uses a lot of CPU (which could be optimized probably if it's just about outputting the same pattern again and again?!).

The remaining issue (if #163 is fixed) then would be still if the json parser should be enabled by default? What's your opinion on this?

**Comment by blueyed** [comment]
@b4n 
You do not appear to use tmpfs then for /tmp, do you? At least your partition for /tmp is much larger than my available free space.

**Comment by b4n** [comment]
> While using `--excmd=number` fixes it, the problem with the first command is that it uses a lot of CPU (which could be optimized probably if it's just about outputting the same pattern again and again?!).

Yes, I didn't check the code thoroughly but it is seems to get more or less CPU stuck in `putc()` when outputing these huge lines.

> The remaining issue (if #163 is fixed) then would be still if the json parser should be enabled by default? What's your opinion on this?

That  it outputs a lot of tags?  I don't know really, but I wouldn't mind at all not to have it enabled by default as I think it's mostly useful as a TOC rather than for generic tag lookup.

> You do not appear to use tmpfs then for /tmp, do you? At least your partition for /tmp is much larger than my available free space.

For the size test I used a direct `-f` to a file on partition with reasonable free space, which avoids the use of a temporary file on /tmp.  Though, it filled up the 58Go I had so I don't know the size it would actually have had -- but it would've been more than 58Go.

**Comment by blueyed** [comment]
Hmm, `ctags -f- cities_light.json > /dev/null` also creates a temporary file for me.

> I don't know really, but I wouldn't mind at all not to have it enabled by default as I think it's mostly useful as a TOC rather than for generic tag lookup.

Yes.

It might have taken up to 72GB/Go probably:

    echo $(( $(ctags -f- cities_light_pp.json | wc -l) * $(wc -c < cities_light.json) / 1024/1024/1024 ))
ctags: Warning: xcmd recognizes /usr/local/libexec/ctags/drivers/coffeetags is not available
72

`number of lines when parsed` * `number of bytes in the context line`

**Comment by b4n** [comment]
> Hmm, `ctags -f- cities_light.json > /dev/null` also creates a temporary file for me.

Yes, you need to use `-f /dir/file` not stdout redirected.

> It might have taken up to 72GB/Go probably:
>
>   […]
>
>`number of lines when parsed` * `number of bytes in the context line`

Yeah, sounds about sensible.  Anyway, *way* too big.

**Comment by blueyed** [comment]
> you need to use -f /dir/file not stdout redirected.

Ah. But why does also `ctags -u` (unsorted) uses a temporary file?
Is there some other processing involved, or could it be dumped directly in this case?

> I didn't check the code thoroughly but it is seems to get more or less CPU stuck in putc() when outputing these huge lines.

This could get improved then probably - and might also benefit the more common case of only a few megabytes of data then.
