### ISSUE TITLE
ctags might fail silently if /tmp is full

### ISSUE THREAD

**Issue by blueyed** [fishman/ctags#202]
When /tmp is full, ctags might fail silently (outputting nothing) (ref: #201):

Using `strace` then it looks like this:

    [pid 18982] stat("/tmp/tags.cP8Y89", {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
    [pid 18982] geteuid()                   = 1000
    [pid 18982] getegid()                   = 1000
    [pid 18982] getuid()                    = 1000
    [pid 18982] getgid()                    = 1000
    [pid 18982] access("/tmp/tags.cP8Y89", R_OK) = 0
    [pid 18982] open("/tmp/tags.cP8Y89", O_WRONLY|O_CREAT, 0666) = 3
    [pid 18982] dup2(3, 1)                  = 1
    [pid 18982] close(3)                    = 0
    [pid 18982] sched_getaffinity(0, 128, {f, 0, 0, 0}) = 32
    [pid 18982] open("/tmp/tags.cP8Y89", O_RDONLY) = 3
    [pid 18982] fadvise64(3, 0, 0, POSIX_FADV_SEQUENTIAL) = 0
    [pid 18982] fstat(3, {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
    [pid 18982] getrlimit(RLIMIT_DATA, {rlim_cur=RLIM64_INFINITY, rlim_max=RLIM64_INFINITY}) = 0
    [pid 18982] getrlimit(RLIMIT_AS, {rlim_cur=RLIM64_INFINITY, rlim_max=RLIM64_INFINITY}) = 0
    [pid 18982] getrlimit(RLIMIT_RSS, {rlim_cur=RLIM64_INFINITY, rlim_max=RLIM64_INFINITY}) = 0
    [pid 18982] open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 4
    [pid 18982] fstat(4, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
    [pid 18982] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff96fab8000
    [pid 18982] read(4, "MemTotal:        8056664 kB\nMemF"..., 1024) = 1024
    [pid 18982] close(4)                    = 0
    [pid 18982] munmap(0x7ff96fab8000, 4096) = 0
    [pid 18982] open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 4
    [pid 18982] fstat(4, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
    [pid 18982] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff96fab8000
    [pid 18982] read(4, "MemTotal:        8056664 kB\nMemF"..., 1024) = 1024
    [pid 18982] close(4)                    = 0
    [pid 18982] munmap(0x7ff96fab8000, 4096) = 0
    [pid 18982] fstat(3, {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
    [pid 18982] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff96fab8000
    [pid 18982] read(3, "", 4096)           = 0
    [pid 18982] lseek(3, 0, SEEK_CUR)       = 0
    [pid 18982] close(3)                    = 0
    [pid 18982] munmap(0x7ff96fab8000, 4096) = 0
    [pid 18982] ftruncate(1, 0)             = 0
    [pid 18982] close(1)                    = 0
    [pid 18982] close(2)                    = 0
    [pid 18982] exit_group(0)               = ?
    [pid 18982] +++ exited with 0 +++
    [pid 18981] <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 18982
    [pid 18981] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=18982, si_status=0, si_utime=0, si_stime=0} ---
    [pid 18981] rt_sigreturn()              = 18982
    [pid 18981] exit_group(0)               = ?
    [pid 18981] +++ exited with 0 +++
    <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 18981
    rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f0f0cbfcc30}, NULL, 8) = 0
    rt_sigaction(SIGQUIT, {SIG_DFL, [], SA_RESTORER, 0x7f0f0cbfcc30}, NULL, 8) = 0
    rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
    --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=18981, si_status=0, si_utime=0, si_stime=0} ---
    open("/tmp/tags.cP8Y89", O_RDONLY)      = 3
    fstat(3, {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
    mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0f0d1ab000
    read(3, "", 4096)                       = 0
    close(3)                                = 0
    munmap(0x7f0f0d1ab000, 4096)            = 0
    unlink("/tmp/tags.cP8Y89")              = 0
    exit_group(0)                           = ?
    +++ exited with 0 +++

**Comment by dtikhonov** [comment]
This is interesting.  In the same vein, it seems that no error-checking is performed when writing individual tag entries to an open file handle -- see `writeCtagsEntry`, for example.

**Comment by masatake** [comment]
@dtikhonov , @blueyed , could you look at https://github.com/bmateusz/ctags/commit/b85937e8a41209b6fadb876a04952795f19eb582 ?

**Comment by blueyed** [comment]
@masatake 
From what I can tell this looks good.

**Comment by masatake** [comment]
Fixed in #244.
