### ISSUE TITLE
incorrect detection of private functions/methods in python

### ISSUE THREAD

**Issue by gotyaoi** [fishman/ctags#216]
The current chunk of code that controls whether a function is public or private is

    /* If a function starts with __, we mark it as file scope.
    * FIXME: What is the proper way to signal such attributes?
    * TODO: What does functions/classes starting with _ and __ mean in python?
    */
    if (strncmp (vStringValue (function), "__", 2) == 0 &&
        strcmp (vStringValue (function), "__init__") != 0)
    {
        tag.extensionFields.access = "private";
        tag.isFileScope = TRUE;
    }
    else
    {
        tag.extensionFields.access = "public";
    }

This is missing a few cases.

* Any name that begins with a single underscore should be considered private. The interpreter does not enforce this, but it's a useful convention.
* Any name inside a class that begins with two underscores but does not end with two underscores undergoes name mangling to _classname__name, to avoid conflicts with child classes using the same name. Double underscore should also be considered private.
* Finally, names that begin two underscores and end with two underscores are "magic". They're used by the interpreter to implement various functionality. They should not be considered private.

The current implementation appears to mark any function/method that begins with two underscores but is not `__init__` as private. This leaves out names beginning with one underscore, and includes names that start with two underscores but also end with two underscores.

`makeClassTag` and `makeVariableTag` do not include any logic to set the access extension field at all right now, as far as I can see.

**Comment by b4n** [comment]
This is already fixed in Geany, we need to import the changes here.  See https://github.com/geany/geany/commit/dd7c20a19470f588eaea6196d864142458d3d5ee for the commit relevant to method access.

**Comment by gotyaoi** [comment]
Ah, very cool. Though, it looks like it's only being called for functions. Do you think it makes sense for it to be applied to variables and classes as well?

**Comment by b4n** [comment]
Good remark.  For member variables, sure.  For classes I'm not sure what the Python guidelines say, but possibly yeah.

**Comment by gotyaoi** [comment]
I think the single leading underscore can be applied to pretty much any name. In a package/module it prevents `from name import *` from grabbing it, which includes classes and module level variables beginning with an underscore.

**Comment by b4n** [comment]
> I think the single leading underscore can be applied to pretty much any name. In a package/module it prevents `from name import *` from grabbing it, which includes classes and module level variables beginning with an underscore.

Indeed, a leading underscore at the module level prevents automatic import, and seem to work with anything (classes, functions, constants).

However, double underscore don't lead to any name mangling, so it's just "protected" at the module level, not private.

Also, when nested inside a function everything is private to that function.

So… at the class level, the access rules should be applied to everything.  At module level, only a leading `_` should be considered, and mean protected.  At the function/method level, everything should be considered private.

But… is it useful to mark function children as anything, as we already have the information through the scope, and as leading underscores don't mean anything?

Once we agreed on what should be done I'll give it a shot.

**Comment by gotyaoi** [comment]
Yeah, the double underscore has no special meaning outside of classes, so it would just be considered the same as a name starting with a single underscore.

I'm not sure protected is appropriate for python though. It's sort of a special case for inheritance that python disregards. I mean, you could say that a single underscore inside a class is protected and a double underscore inside a class is private, maybe? Certainly, at the module level things should just be private I think.

I don't think variables inside functions are even tagged at all right now, which seems fine as they're not accessible from outside the function regardless, so probably no need to worry about that. On the other hand, nested functions are tagged, even though they're not accessible from the outside either...

**Comment by b4n** [comment]
> I'm not sure protected is appropriate for python though. It's sort of a special case for inheritance that python disregards. I mean, you could say that a single underscore inside a class is protected and a double underscore inside a class is private, maybe?

That's what I did in the aforementioned patch (double underscore (name mangling) meaning private, and single meaning protected).  I know Python doesn't really have such concepts, but that was the closest thing I could think of (and what was already used by the parser, too).
And while I agree it's not exactly Pythonish, it seems good enough to me -- the information is mostly correct, and in the context of Python shouldn't be misleading.

> Certainly, at the module level things should just be private, not protected, I think.

Well, I don't know, and that's one of the questions that should be answered.  Technically at the module level it resembles more the single underscore at the class level ("protected"), as it is relatively/very easy to still access those.  For example you can do `from module import __something` and it will work just fine.
This even suggests that setting an "accessibility" information on those may be wrong -- but OTOH as you mentioned `from module import *` wouldn't import it, so it does *something*.

> I don't think variables inside functions are even tagged at all right now, which seems fine as they're not accessible from outside the function regardless, so probably no need to worry about that.

No, variables inside functions are just not extracted at all, so we don't need to worry about those.

> On the other hand, nested functions are tagged, even though they're not accessible from the outside either...

Yes.  The question if for nested classes and functions: what accessibility should they be tagged with.  None, because anyway as we have the nesting information it's not important? (anything inside a function is private, so there's no point in saying so again?  This leads to the question of whether *anything* should have accessibility information, as it can be inferred from hierarchy and type.  But having accessibility information helps a caller not to need intimate Python knowledge by reporting the info in a generic way.
Or mark them private?  This is somewhat what they are, but it's also a bit artificial.

Anyway, currently the decision how to tag accessibility does not depend on scope but only tag type, so this should probably be changed.

**Comment by b4n** [comment]
Proposed solution (commit is on top of [my python branch](/b4n/fishman-ctags/commits/python), see PR #217): f93113d0943957f7052dd46c5a320a7e13cca4b9

**Comment by gotyaoi** [comment]
Ah, I must have reversed your meaning when reading your comment, sorry. Anyway, when you put it that way, protected at the module level does make sense. I personally think your patch is good, though some of the parameter lists in python.c seem to have flown off to the right :)

**Comment by b4n** [comment]
> Anyway, when you put it that way, protected at the module level does make sense. I personally think your patch is good

Good, if we reached an understanding I'll PR it :)  Not sure exactly if I should add it to the current PR though, so I might delay it a bit for #217 to be merged.

> though some of the parameter lists in python.c seem to have flown off to the right :)

Hum, normally this file uses tabs of width 4, but GitHub doesn't get that.  Though, you're right and the style in *python.c* is slightly different than the other files, so I fixed the patch to adhere to it.  Fixed patch is 22c4cbe47e4985aefede1dee9dbeca382ebd5105.

**Comment by gotyaoi** [comment]
Hi again. First, wanted to say thanks for the patch. Just got around to installing it and it's much nicer than it was before. I did run into one edge case though. While the dunder names (__name__) are handled properly inside classes, there exists some small cases where they will exist at the module level, for instance __all__ and __version__. I didn't notice it before, but the current version marks these as protected, while they're arguably part of a package's public interface.

It's such a small case that it may not be necessary to change, but I just thought I'd bring it up.

**Comment by b4n** [comment]
If this is important to you I guess we could add something like this:

```diff
diff --git a/python.c b/python.c
index 4b63131..b79a502 100644
--- a/python.c
+++ b/python.c
@@ -155,7 +155,8 @@ static pythonAccess accessFromIdentifier (const vString *const ident,
     else if (len < 1 || p[0] != '_')
         return A_PUBLIC;
     /* "__...__": magic methods */
-    else if (kind == K_MEMBER && parent_is_class &&
+    else if (((kind == K_MEMBER && parent_is_class) ||
+              (kind == K_VARIABLE && ! has_parent)) &&
              len > 3 && p[1] == '_' && p[len - 2] == '_' && p[len - 1] == '_')
         return A_PUBLIC;
     /* "__...": name mangling */
```

**Comment by gotyaoi** [comment]
If it's not too much trouble, I think it would be a good addition, yes.
