### ISSUE TITLE
Allow to change program name e.g. ctags -> exctags

### ISSUE THREAD

**Issue by jonthn** [fishman/ctags#262]
On certain systems (mainly BSD ones) there is already a 'ctags' tool provided by the base system (see for example this man page for FreeBSD : https://www.freebsd.org/cgi/man.cgi?query=ctags&manpath=FreeBSD+10.1-RELEASE )

In that case almost all packaging system have to 'patch' the source code to change the names of the tool (again from FreeBSD see : http://svnweb.freebsd.org/ports/head/devel/ctags/files/ )

Considering this it would be great to have an option similar to ```--program-prefix``` (see Automake documentation : http://www.gnu.org/software/automake/manual/html_node/Renaming.html ) in order to change the program name (both ctags & etags) and change the man page accordingly.

**Comment by jonthn** [comment]
See PR #287

**Comment by masatake** [comment]
#287 is merged. Thank you.
