### ISSUE TITLE
Broken --quiet when used as command line option

### ISSUE THREAD

**Issue by UmkaDK** [fishman/ctags#266]
`--quiet` option appears to be broken when used from the command line as opposite to the `.ctags` file. When specified inside the `.ctags` file, `--quiet` works as expected.

```
$ cat ~/.ctags
--totals=no
--recurse=yes
--exclude=(.svn|.git)
--exclude=*/build/*
--fields=+i
$ ctags test.rb --quiet
ctags: Notice: xcmd recognizes /usr/local/Cellar/ctags-fishman/HEAD/libexec/ctags/drivers/coffeetags is not available
$ ctags test.rb --quiet=yes
ctags: Notice: xcmd recognizes /usr/local/Cellar/ctags-fishman/HEAD/libexec/ctags/drivers/coffeetags is not available
$ echo "--quiet=yes" >> .ctags
$ ctags test.rb
$ 
```

This issue might be related to 
 - coffeetags not found? (#131)
 - Remove code using stderr directly and introduce --quite option (#195)

**Comment by masatake** [comment]
How about  moving the --quiet option before the input file name?

    $ ctags --quiet  test.rb

**Comment by UmkaDK** [comment]
Good point! :) `ctags --quiet  test.rb` works as expected.

**Comment by masatake** [comment]
(NOTE: I should write about how the order of option parsing to internal.rst.)

**Comment by huanghx1990** [comment]
i will try IT tomorrow ～

**Comment by huanghx1990** [comment]
and now the  first issue is pass，how about the second ？

**Comment by masatake** [comment]
See #318. Not #266. People are working on the issue.
