### ISSUE TITLE
regexp patterns don't seem to work on solaris 11(12)

### ISSUE THREAD

**Issue by tarzanek** [fishman/ctags#269]
I tried with Solaris 12 
ctags 5.8 , ctags 5.9 and ctags from this fork :)

Note that debian ctags 5.9 works with below command, prints (so this is expected on Solaris, too):
```
bug15890        bug15890.hs      /^bug15890 x = x + 1$/;"        functions       line:26
x       bug15890.hs      /^bug15890 x = x + 1$/;"        functions       line:26
```

And I failed miserably
command to repro:
```
$ ctags -f"-" --verbose --options=./ctags.options bug15890.hs
```
output on Solaris is empty

my input file:

```
bug15890.hs
-- -*- coding: utf-8 -*-

{-
   Test for bug #15890. Ctags and JFlex do not agree on line
   numbering. JFlex regards \u000B, \u000C, \u0085, \u2028 and \u2029
   as line terminator, whereas ctags doesn't. If one of these
   characters occurred in a file, definitions that came after it would
   not be recognized as definitions by the xrefs, since the line
   numbers didn't match what ctags returned.
-}

-- This line contains \u000B: 


-- This line contains \u000C: 

-- This line contains \u0085: Â


-- This line contains \u2028: â¨

-- This line contains \u2029: â©

{-
   Now add a definition for the tests to check.
-}

bug15890 x = x + 1
```

my ctags option file:
```
cat ./ctags.options
--fields=-anf+iKnS
-u
--excmd=pattern
--langdef=haskell
--langmap=haskell:.hs.hsc
--regex-haskell=/^\s*class\s+([a-zA-Z0-9_]+)/\1/c,classes/
--regex-haskell=/^\s*data\s+([a-zA-Z0-9_]+)/\1/t,types/
--regex-haskell=/^\s*newtype\s+([a-zA-Z0-9_]+)/\1/t,types/
--regex-haskell=/^\s*type\s+([a-zA-Z0-9_]+)/\1/t,types/
--regex-haskell=/^([a-zA-Z0-9_]+).*\s+={1}\s+/\1/f,functions/
--regex-haskell=/\s+([a-zA-Z0-9_]+).*\s+={1}\s+/\1/f,functions/
--regex-haskell=/^(let|where)\s+([a-zA-Z0-9_]+).*\s+={1}\s+/\2/f,functions/
--regex-haskell=/\s+(let|where)\s+([a-zA-Z0-9_]+).*\s+={1}\s+/\2/f,functions/
```

I will try on Solaris 10, too ;)

**Comment by tarzanek** [comment]
Same on S10, this seems to be some library mismatch for regexp on Solaris , regular expresions seem ok (they do work on linux)
but on Solaris they just don't get any hit (I tried simplify them
and e.g. --regex-haskell=/^([a-zA-Z0-9_]+)/\1/f,functions/  gets me a hit on above file ... )

**Comment by tarzanek** [comment]
checked regex.h on both and they seem to differ a bit ...
so it seems GNU is not really POSIX
http://www.gnu.org/savannah-checkouts/gnu/libc/manual/html_node/Regular-Expressions.html
oh well :)

**Comment by tarzanek** [comment]
seems I should try to rewrite above to POSIX ... http://en.wikipedia.org/wiki/Regular_expression#POSIX_basic_and_extended
or got a better advice? :)

**Comment by tarzanek** [comment]
seems replacing \s 
with [ \t\r\n\v\f]
got me going ... weird

**Comment by vhda** [comment]
AFAIK, `\s` syntax is generally not supported in regular expressions.
For a more standard support, you should use the following character class `[[:space:]]` instead of `\s`.

**Comment by tarzanek** [comment]
yep, [[:space:]] works  OK, too .. good, thnx @vhda!

**Comment by masatake** [comment]
@tarzanek, please close this if you are o.k.
BTW, Do your options for haskell work well? (I don't know well aobut haskell.)
Do you have interests to merge the options to ctags source tree?

**Comment by tarzanek** [comment]
I have ctags and scala options, they should work, but I guess having a proper parser would be better, no?
fwiw - options:
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/analysis/Ctags.java#L97

thank you!

**Comment by tarzanek** [comment]
(oh yes, and I will rewrite them with [:space:] ... soon)
