### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by lmartins** [fishman/ctags#273]
Any chance you could add instructions on how to install this?
Im trying to make Vim understand tags from Sass files.

Thanks.

**Comment by b4n** [comment]
Like most Autotools-based projects, you just need to do:

```console
$ autoreconf -vfi
$ ./configure --prefix=/where/you/want # defaults to /usr/local
$ make
$ make install # may require extra privileges depending on where to install
```

The `ctags` executable will be in `$prefix/bin/`.

This said, I don't think there currently is built-in SASS support, is there?

**Comment by lmartins** [comment]
yeah, im pretty noob about this kind of tools.
Honestly didn't quite understand your instruction, which I thank you anyway, so i'll keep digging to better understand all that's involved.

From what I've read, Sass should be partially supported according to http://stackoverflow.com/questions/13276209/how-to-browse-sass-css-files-with-vim-effectively

Thanks again.
