### ISSUE TITLE
Handle files starting with "#compdef" as zsh/sh

### ISSUE THREAD

**Issue by blueyed** [fishman/ctags#282]
With zsh's source (git://git.code.sf.net/p/zsh/code) and installation, there are many completion scripts, which start with a line like the following:

    #compdef git git-cvsserver git-receive-pack git-upload-archive git-upload-pack git-shell gitk tig

Most of them do not have emacs/vim modelines.

It would be nice if ctags would consider these to be sh/zsh, when `--guess-language-eagerly` is used.

`#autoload` should be handled in the same way.

**Comment by masatake** [comment]
Interesting. I prepared a PR.
