### ISSUE TITLE
Handle "inl" extension as C++

### ISSUE THREAD

**Issue by blueyed** [fishman/ctags#305]
Neovim uses `.inl` files, which are ignored by ctags.

For reference, the following extensions are handled as cpp by Vim:

    runtime/filetype.vim
    372:au BufNewFile,BufRead *.cxx,*.c++,*.hh,*.hxx,*.hpp,*.ipp,*.moc,*.tcc,*.inl setf cpp

**Comment by masatake** [comment]
Fixed in a88f344 .

**Comment by blueyed** [comment]
Thanks, that works!
