### ISSUE TITLE
Wrong makeTagEntry usage (sf-bug:356)

### ISSUE THREAD

**Issue by masatake** [fishman/ctags#324]
See http://sourceforge.net/p/ctags/bugs/365/

**Comment by b4n** [comment]
Other languages have the same problem.

One possible way to go would be to require passing a `kindOption` array to `makeTagEntry()` so it could itself check whether to create the tag or not.

This however requires a few non-trivial changes, the most important ones being those under *main/* (parsers are almost trivial to fix, but *c.c* that require a little more work but it totally doable).

The other solution is to simply add the check in each parser missing it (most parsers have it, but not all).

**Comment by masatake** [comment]
@b4n, thank you for fixing quickly. However, I want to think this issue a bit more because this is related to the one of my biggest questions about ctags.

If this issue can be handled main/ side, this kind of bug can be suppressed forever.
As you write, passing a kindOption array is one of solution. I think this one is worth trying.

If accessing the current parserDefinition from makeTagEntry () is permitted, we don't have to pass a kindArray to makeTagEntry. By Introducing getCurrentLanguage or adding parser field to tagsEntryInfo structure, we can pass the parserDefinition object to makeTagEntry(). However, this may break isolation of code. I am not sure.

During reading source code of ctags, I found that accessing to a parserDefinition is  limited in many areas. For me the the limitation is a bit too string. @b4n, how do you think? It seems that this limitation is very basic design decision of ctags. However it is not enough clear for me.

**Comment by masatake** [comment]
I would like to try fixing this in main/ side.
Macros in read.h are the public interface of parserDefinition.

step1. Add isEnabledKindInSourceLanguage(c) to read.h.
step2. Implement makeTagEntryWithKindCheck based on isEnabledKindInSourceLanguage.
step3. use makeTagEntryWithKindCheck where @b4n patched in this pull request.

It will not be so difficult because the places where patching is needed are enumerated by @b4n.

**Comment by masatake** [comment]
@b4n, I implemented step1 and step2. Could you look at them?
The name of functions are a bit too long. If o.k. I will do step 3 bsaed on your PR.
