### ISSUE TITLE
Request: Start versioning this project

### ISSUE THREAD

**Issue by tecfu** [fishman/ctags#334]
No information about the version of this codebase is readily apparent in the README.md or otherwise.

Before finding this repository on github, I installed Exuberant Ctags on Ubuntu 14.04 via 

```
apt-get install exuberant-ctags
````

The command:
```
ctags --version 
```
only yields information about the date compiled. 

I think its reasonable to believe that users would appreciate versioning for this project, for obvious reasons.

**Comment by masatake** [comment]
We will provide a different name from "Exuberant Ctags".
We are discussing the name now. Maybe it will be universal ctags.
The name will be printed with ctags --version.

Is it enough?

**Comment by tecfu** [comment]
My response to the suggestion of a name change is as follows:

### "exuberant ctags" still has powerful brand value

- Many, if not most stackoverlow questions about ctags have references to exuberant ctags
- This project will lose the search benefit of that affiliation
- Users who want to a quick, simple solution will be unlikely to find this project

### "exuberant ctags" on sourceforge is obviously dead.

- It seems highly unlikely that the original author is going to resume development on github after 6 years of neglect
- This project is the only one attempting to maintain the codebase, and in my opinion it deserves to keep the name

### "exuberant ctags" is already included in the standard ubuntu repositiories, and probably others

- Why not just version this repository, and follow the semver convention - starting at 2.0.0? See: https://github.com/mojombo/semver

- Has anyone from this project reached out to the original author to ask if they can take over? 
It appears to be Darren Hiebert / http://darrenhiebert.com
His email address is on his website.

**Comment by ffes** [comment]
You are right that exuberant is still a strong name, even after not releasing for almost 6 years.

We have contacted him over half a year ago. But he wants to stick with SVN at SourceForge. Many have tried to convince him but without any luck. See the archives of the ctags-devel mailing list and PR #182 for more details. We have to chose another name, exuberant is his name.

**Comment by tecfu** [comment]
Thank you both for taking the time to respond. I had no idea this had been discussed and contemplated in such depth previously.

While not a contributor, given https://github.com/fishman/ctags/pull/182 it appears there is absolutely no way forward but to fork. I'd vote for it.
