### ISSUE TITLE
SQL parser always produces fully-qualified tags

### ISSUE THREAD

**Issue by dtikhonov** [fishman/ctags#96]
I use tags to aid me browse through a large Toad dump of Oracle schema.  There are large packages; they contains cursors, procedures, and so on.  sql.c only creates fully qualified tags, so if the package is PACKAGE and cursor is CURSOR, the tag created is PACKAGE.CURSOR.  The code:

~~~
static void makeSqlTag (tokenInfo *const token, const sqlKind kind)
{
    vString *   fulltag;

    if (SqlKinds [kind].enabled)
    {
        /*
         * If a scope has been added to the token, change the token
         * string to include the scope when making the tag.
         */
        if ( vStringLength(token->scope) > 0 )
        {
            fulltag = vStringNew ();
            vStringCopy(fulltag, token->scope);
            vStringCatS (fulltag, ".");
            vStringCatS (fulltag, vStringValue(token->string));
            vStringTerminate(fulltag);
            vStringCopy(token->string, fulltag);
            vStringDelete (fulltag);
        }
        makeConstTag (token, kind);
    }
}
~~~

However, inside the package, the cursor is referred to by the short name, simply CURSOR.  This makes it impossible to jump to the cursor definition.  This seems like a bug to me.

P.S.  To work around this issue, I do

~~~
perl -ne 'print; s/^.+?\.// and print' tags | LC_ALL=C sort > all-tags && mv all-tags tags
~~~

**Comment by masatake** [comment]
The idea I showed in the last comment can be implemented based on cork API.
